- name: conditional loop 
  hosts: local
  connection: local
  vars:
    Number: 18
  tasks:
  - name: print a number is less than or greater than 100
    ansible.builtin.debug:
      msg: "given number {{Number}} is less than 100"
    when: Number <= 100
      

  - name: print a number is less than or greater than 100
    ansible.builtin.debug:
      msg: "given number {{Number}} is greater than 100"
    when: Number > 100
      
