- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "ramesh,suresh,ved ,viyaan"
  tasks:
  - name: "check undefined variables" 
    ansible.builtin.debug:
     msg: "Heloo, {{ persons | default('ramesh')}}"

  - name: print names
    ansible.builtin.debug:
     msg: "Heloo , {{ persons | split (',')}}" 
  
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10 HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info : {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - { 'key': 'name', 'value': 'ansible' }
      - { 'key': 'duration' , 'value': '120HR' }
      - { 'key': 'trainer' , 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info : {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"
 
  - name: convert to lowercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not 
    vars:
      ip: "192.165.2.1"
    ansible.builtin.debug:
      msg: " {{ ip | ansible.utils.ipaddr }}"