- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls ouput to a file
    ansible.builtin.shell: " ls -lrt > /tmp/output.txt "
    register: command_result 

  - name: print the outcome
    ansible.builtin.debug: 
      msg: "{{ command_result }}"

  - name: command ls output
    ansible.builtin.command: "ls -lrt"
    register: command_result

  - name: print the outcome of ls 
    ansible.builtin.debug:
      msg: "{{ command_result }}"
