- name: create user 
  hosts: local
  connection: local
  become: yes 
  tasks:
  - name: verify whether user exist or not
    ansible.builtin.command: id devsecops
    register: output
    ignore_errors: true

  - name: create users 
    ansible.builtin.command: useradd devsecops
    when: output.rc != 0

  - name: user already exists
    ansible.builtin.debug:
      msg: "user already exist" 
    when: output.rc == 0 
