- name: install nginx on dynamic servers 
  hosts: dynamic_frontend 
  become: yes 
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
    name: nginx
    state: installed

  - name: start the nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 

















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































