- name: install and start nginx
  hosts: frontend
  become: yes #provides root access 
  tasks:
    - name: Installation of nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: starting nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes 

