- name: install and start nginx
  hosts: frontend
  tasks:
    - name: Installation of nginx
      ansible.builtin.pacakage:
        name: nginx
        state: present

    - name: starting nginx
      ansible.builtin.service:
        state: started
        enabled: yes 

