- name: Variables from different file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: calling variables from course.yaml
    ansible.builtin.debug:
      msg: " course name is {{ COURSE }}, duration of {{ DURATION }} and trainer is {{ TRAINER }} ..{{ GREETING }} "