- name: variables using prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: enter your username
    private: false
  - name: PASSWORD
    prompt: enter your Password
    private: true

  tasks:
    ansible.builtin.debug:
      msg: "username is {{ USERNAME }} password is {{ PASSWORD }}"
